# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstats',
            name='margin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
